version: '3.8'

services:
  postgres:
    image: postgres:14
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: chatadmin
      POSTGRES_PASSWORD: chatpassword
      POSTGRES_DB: tokenized_chat
    ports:
      - "5432:5432"

  server:
    build:
      context: ./server
    environment:
      JWT_SECRET: dev_secret_key
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USERNAME: chatadmin
      DB_PASSWORD: chatpassword
      DB_DATABASE: tokenized_chat
      PORT: 4000
    ports:
      - "4000:4000"
    depends_on:
      - postgres

  client:
    build:
      context: ./client
    ports:
      - "3000:80"
    depends_on:
      - server

volumes:
  pgdata:
